FROM continuumio/anaconda2
LABEL Jee Vang, Ph.D. "vangjee@gmail.com"
ENV PATH /opt/conda/bin:$PATH
ENV PYBBN_VERSION 0.2.2
ENV PY_VERSION py27
ENV PYPI_REPO testpypi
RUN apt-get update \
    && apt-get upgrade -y \
    && apt-get install build-essential -y
COPY . /py-bbn
RUN conda install --file /py-bbn/requirements.txt -y
RUN cd /py-bbn \
    && make \
    && python setup.py sdist bdist bdist_wheel \
    && twine check dist/* \
    && cd /py-bbn/docs \
    && make html \
    && /py-bbn/publish.sh