FROM continuumio/anaconda3
LABEL Jee Vang, Ph.D. "vangjee@gmail.com"
ENV PATH /opt/conda/bin:$PATH
RUN apt-get update \
    && apt-get upgrade -y \
    && apt-get install build-essential -y
COPY . /py-bbn
RUN conda install --file /py-bbn/requirements.txt -y
RUN cd /py-bbn \
    && make \
    && python setup.py sdist bdist bdist_wheel \
    && twine check dist/* \
    && cd /py-bbn/docs \
    && make html